FROM ubuntu:jammy
LABEL maintainer="Vivo Developers <dev@vivo.org>"
LABEL description="Dockerised VivoCore"

ARG USER_ID
ARG GROUP_ID
ARG TAG
ARG GITHUB_REPOSITORY

ENV HOME /home/vivo

# add user with specified (or default) user/group ids
ENV USER_ID ${USER_ID:-1000}
ENV GROUP_ID ${GROUP_ID:-1000}
RUN groupadd -g ${GROUP_ID} vivo && \
    useradd -u ${USER_ID} -g vivo -s /bin/bash -m -d /home/vivo vivo  && \
    mkdir /home/vivo/.vivocore && \
    chown ${USER_ID}:${GROUP_ID} -R /home/vivo

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN echo "https://github.com/${GITHUB_REPOSITORY}/releases/download/v${TAG}/vivocore-${TAG}-$arch.tar.gz"

RUN mach=$(uname -m) \
      && case $mach in aarch64) arch="aarch64-linux-gnu"; ;; x86_64) arch="x86_64-linux-gnu"; ;;  *) echo "ERROR: Machine type $mach not supported."; ;; esac \
      && wget https://github.com/${GITHUB_REPOSITORY}/releases/download/v${TAG}/vivocore-${TAG}-$arch.tar.gz -P /tmp \
      && tar -xvf /tmp/vivocore-*.tar.gz -C /tmp/ \
      && find /tmp/vivocore*/bin -type f ! -name 'vivo-qt' -exec cp {} /usr/local/bin \; \
      && rm -rf /tmp/vivocore* \
      && chmod a+x /usr/local/bin/*

RUN apt-get update && \
    apt list --installed && \
    apt-get -y purge \
    wget \
    ca-certificates \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

USER vivo

VOLUME ["/home/vivo"]

COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 9998 9999 19998 19999

WORKDIR /home/vivo
