// Copyright (c) 2012-2021 The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#if defined(HAVE_CONFIG_H)
#include <config/bitcoin-config.h>
#endif

#include <clientversion.h>
#include <util/translation.h>

#include <tinyformat.h>

#include <sstream>
#include <string>
#include <vector>

/**
 * Name of client reported in the 'version' message. Report the same name
 * for both vivod and vivo-qt, to make it harder for attackers to
 * target servers or GUI users specifically.
 */
const std::string CLIENT_NAME("Vivo Core");


#ifdef HAVE_BUILD_INFO
#include <obj/build.h>
// The <obj/build.h>, which is generated by the build environment (share/genbuild.sh),
// could contain only one line of the following:
//   - "#define BUILD_GIT_DESCRIPTION ...", if the top commit is not tagged
//   - "// No build information available", if proper git information is not available
#endif

//! git will put "#define ARCHIVE_GIT_DESCRIPTION ..." on the next line inside archives. $Format:%n#define ARCHIVE_GIT_DESCRIPTION "%(describe:abbrev=12)"$

#if CLIENT_VERSION_IS_RELEASE
    #define BUILD_DESC "v" PACKAGE_VERSION
    #define BUILD_SUFFIX ""
#else
    #if defined(BUILD_GIT_DESCRIPTION)
        // build in a cloned folder
        #define BUILD_DESC BUILD_GIT_DESCRIPTION
        #define BUILD_SUFFIX ""
    #elif defined(ARCHIVE_GIT_DESCRIPTION)
        // build in a folder from git archive
        #define BUILD_DESC ARCHIVE_GIT_DESCRIPTION
        #define BUILD_SUFFIX ""
    #else
        #define BUILD_DESC "v" PACKAGE_VERSION
        #define BUILD_SUFFIX "-unk"
    #endif
#endif

std::string FormatVersion(int nVersion)
{
    // VIVO_R5G1C_FOUR_PART_VERSION
    // Keep the modern three-field numeric encoding for ordering,
    // but display Vivo releases as major.minor.patch.revision.
    const int revision = nVersion == CLIENT_VERSION ? CLIENT_VERSION_REVISION : 0;
    return strprintf("%d.%d.%d.%d",
        nVersion / 10000,
        (nVersion / 100) % 100,
        nVersion % 100,
        revision);
}

std::string FormatFullVersion()
{
    // VIVO_R5G1F_CANONICAL_RELEASE_VERSION
    // The public VIVO release identity must come from the canonical
    // numeric client version, not from an older Git tag/describe string.
    return "v" + FormatVersion(CLIENT_VERSION);
}

/**
 * Format the subversion field according to BIP 14 spec (https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki)
 */
std::string FormatSubVersion(const std::string& name, int nClientVersion, const std::vector<std::string>& comments)
{
    std::ostringstream ss;
    ss << "/";
    ss << name << ":" << FormatVersion(nClientVersion);
    if (!comments.empty())
    {
        std::vector<std::string>::const_iterator it(comments.begin());
        ss << "(" << *it;
        for(++it; it != comments.end(); ++it)
            ss << "; " << *it;
        ss << ")";
    }
    ss << "/";
    return ss.str();
}

std::string CopyrightHolders(const std::string& strPrefix, unsigned int nStartYear, unsigned int nEndYear)
{
    const auto copyright_devs = strprintf(_(COPYRIGHT_HOLDERS).translated, COPYRIGHT_HOLDERS_SUBSTITUTION);
    std::string strCopyrightHolders = strPrefix + strprintf(" %u-%u ", nStartYear, nEndYear) + copyright_devs;

    // Check for untranslated substitution to make sure Dash Core copyright is not removed by accident
    if (copyright_devs.find("Dash Core") == std::string::npos) {
        strCopyrightHolders += "\n" + strPrefix + strprintf(" %u-%u ", 2014, nEndYear) + "The Dash Core developers";
    }
    // Check for untranslated substitution to make sure Bitcoin Core copyright is not removed by accident
    if (copyright_devs.find("Bitcoin Core") == std::string::npos) {
        strCopyrightHolders += "\n" + strPrefix + strprintf(" %u-%u ", 2009, nEndYear) + "The Bitcoin Core developers";
    }
    return strCopyrightHolders;
}

std::string LicenseInfo()
{
    const std::string URL_SOURCE_CODE = "<https://github.com/KingricharVD/vivo>";

    return CopyrightHolders(_("Copyright (C)").translated, 2014, COPYRIGHT_YEAR) + "\n" +
           "\n" +
           strprintf(_("Please contribute if you find %s useful. "
                       "Visit %s for further information about the software.").translated, PACKAGE_NAME, "<" PACKAGE_URL ">") +
           "\n" +
           strprintf(_("The source code is available from %s.").translated, URL_SOURCE_CODE) +
           "\n" +
           "\n" +
           _("This is experimental software.").translated + "\n" +
           strprintf(_("Distributed under the MIT software license, see the accompanying file %s or %s").translated, "COPYING", "<https://opensource.org/licenses/MIT>") +
           "\n";
}
